labels:
  # describe priority
  - name: 'patch'
    color: '207de5'
  - name: 'minor'
    color: '009800'
  - name: 'major'
    color: 'e11d21'
  - name: 'pedantic'
    color: 'd1e4fa'
  - name: 'bug'
    color: 'fc2929'
  - name: 'critical'
    color: 'fc2929'

  # state on a board
  - name: 'in progress'
    color: 'ededed'
  - name: 'review'
    color: 'ededed'
  - name: 'wip/poc'
    color: 'ededed'
  - name: 'ready'
    color: 'ededed'
  - name: 'won`t fix'
    color: 'ededed'

  # issue classes
  - name: 'help wanted'
    color: '128A0C'
  - name: 'good first issue'
    color: '5319e7'
  - name: 'question'
    color: 'cc317c'
  - name: 'Easy Pick'
    color: 'd7e102'
  - name: 'DX'
    color: '5319e7'
  - name: 'UX'
    color: '19E791'
    color: '333333'
  - name: 'discussion'
    color: 'cc317c'
  - name: 'enhancement'
    color: '02d7e1'
  - name: 'feature'
    color: '207de5'
  - name: 'nice to have'
    color: '0052cc'

  # persistence layer
  - name: 'ORM'
    color: 'bfd4f2'
  - name: 'PHPCR'
    color: 'bfd4f2'

  # else
  - name: 'pending author'
    color: 'ededed'
  - name: 'blocked'
    color: 'cccccc'
  - name: 'duplicate'
    color: 'cccccc'

packages:
  symfony: symfony/symfony
  core_bundle: symfony-cmf/core-bundle
  website: symfony-cmf/symfony-cmf-website
  seo_bundle: symfony-cmf/seo-bundle

