admin-bundle:
    documentation_badge_slug: sonata-project-sonataadminbundle
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
                sonata-project/block-bundle: ['5.x-dev as 4.999']
                sonata-project/form-extensions: ['2.x-dev as 1.999']

block-bundle:
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['4.4.*', '5.4.*', '6.2.*', '6.3.*']

classification-bundle:
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

doctrine-extensions:
    has_documentation: false
    has_test_kernel: false
    branches:
        3.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
        2.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']

doctrine-mongodb-admin-bundle:
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

doctrine-orm-admin-bundle:
    documentation_badge_slug: sonata-project-doctrineormadminbundle
    has_platform_tests: true
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

entity-audit-bundle:
    excluded_files:
        - README.md
    has_documentation: false
    has_test_kernel: false
    has_platform_tests: true
    branches:
        2.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        1.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

exporter:
    documentation_badge_slug: sonata-project-exporter
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        3.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

formatter-bundle:
    branches:
        6.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        5.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

form-extensions:
    has_test_kernel: false
    branches:
        2.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            frontend_tests: true
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        1.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            variants:
                symfony/symfony: ['4.4.*', '5.4.*', '6.2.*', '6.3.*']

intl-bundle:
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        3.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

media-bundle:
    documentation_badge_slug: sonata-project-sonatamediabundle
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        4.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

page-bundle:
    branches:
        5.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
                sonata-project/block-bundle: ['5.x-dev as 4.999']
        4.x:
            php: ['8.0', '8.1', '8.2']
            frontend: true
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
                sonata-project/block-bundle: ['5.x-dev as 4.999']

seo-bundle:
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        3.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

translation-bundle:
    branches:
        4.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        3.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

twig-extensions:
    documentation_badge_slug: sonata-project-twig-extensions
    branches:
        3.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        2.x:
            php: ['8.0', '8.1', '8.2']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']

user-bundle:
    branches:
        6.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
        5.x:
            php: ['8.0', '8.1', '8.2']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['5.4.*', '6.2.*', '6.3.*']
