seo-bundle:
  description: |
    "This bundle is part of the [Symfony Content Management Framework (CMF)](http://cmf.symfony.com/)
    and licensed under the [MIT License](LICENSE).

    It provides a solution to make content bundles
    aware for Search Engine Optimisation (SEO)."
  branches:
    master:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
    "2.0":
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
