admin-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_block: ['3']
        symfony_maker: ['1.7']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_block: ['3']
        symfony_maker: ['1.7']

admin-search-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
        ruflin_elastica: ['2']
    1.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
        ruflin_elastica: ['2']

article-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    1.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']

block-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        # https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/131844587#L222
        #sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        # This has to be resolved: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/130298942#L230
        #sonata_admin: ['3']

cache:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.2', '7.3']
    2.x:
      php: ['7.1', '7.2', '7.3']

cache-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']

classification-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']

classification-media-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']

comment-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']

core-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']

dashboard-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

datagrid-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']

doctrine-extensions:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.2', '7.3']
    1.x:
      php: ['7.1', '7.2', '7.3']

doctrine-mongodb-admin-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      services: [mongodb]
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      services: [mongodb]
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']

doctrine-orm-admin-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']

doctrine-phpcr-admin-bundle:
  excluded_files:
    - phpunit.xml.dist
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
        sonata_block: ['3']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_admin: ['3']
        sonata_block: ['3']

easy-extends-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']

ecommerce:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['2.8']

exporter:
  excluded_files:
    - README.md
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        doctrine_odm: ['1']
      services: [mongodb]
    2.x:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        doctrine_odm: ['1']
      services: [mongodb]

formatter-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_block: ['3']
    4.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_block: ['3']

form-extensions:
  docs_target: false
  excluded_files:
    - docs/requirements.txt
  branches:
    master:
      php: ['7.2', '7.3']
      phpunit_version: 8
    1.x:
      php: ['7.2', '7.3']
      phpunit_version: 8

google-authenticator:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.2', '7.3']
    2.x:
      php: ['7.1', '7.2', '7.3']

intl-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_user: ['3']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_user: ['3']

media-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      services: [mongodb]
      versions:
        symfony: ['3.4']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      services: [mongodb]
      versions:
        symfony: ['3.4']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']

news-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']

notification-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']

page-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

sandbox:
  excluded_files:
    - phpunit.xml.dist

seo-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_block: ['3']
        sonata_admin: ['3']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_block: ['3']
        sonata_admin: ['3']

timeline-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

translation-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']
    2.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        sonata_core: ['3']
        sonata_admin: ['3']

twig-extensions:
  docs_target: false
  excluded_files:
    - docs/requirements.txt
  branches:
    master:
      php: ['7.2', '7.3']
    1.x:
      php: ['7.2', '7.3']

user-bundle:
  branches:
    master:
      php: ['7.2', '7.3']
      versions:
        symfony: ['3.4']
        fos_user: ['2']
        sonata_core: ['3']
        sonata_admin: ['3']
    4.x:
      php: ['7.1', '7.2', '7.3']
      versions:
        symfony: ['3.4']
        fos_user: ['2']
        sonata_core: ['3']
        sonata_admin: ['3']
