admin-bundle:
    documentation_badge_slug: sonata-project-sonataadminbundle
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            frontend: true
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            frontend: true
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
                sonata-project/block-bundle: ['5.x-dev as 5.0']

block-bundle:
    branches:
        5.x:
            php: ['8.0', '8.1']
            variants:
                symfony/symfony: ['5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

classification-bundle:
    rector: false
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

doctrine-extensions:
    rector: false
    has_documentation: false
    has_test_kernel: false
    branches:
        2.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']
        1.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']

doctrine-mongodb-admin-bundle:
    rector: false
    phpunit_extensions: ['panther']
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb', 'zip']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb', 'zip']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

doctrine-orm-admin-bundle:
    rector: false
    phpunit_extensions: ['panther']
    documentation_badge_slug: sonata-project-doctrineormadminbundle
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['zip']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['zip']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

entity-audit-bundle:
    rector: false
    excluded_files:
        - README.md
    has_documentation: false
    has_test_kernel: false
    branches:
        2.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        1.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

exporter:
    rector: false
    documentation_badge_slug: sonata-project-exporter
    has_test_kernel: false
    branches:
        3.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        2.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

formatter-bundle:
    rector: false
    has_test_kernel: false
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['zip']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.3', '7.4', '8.0']
            php_extensions: ['zip']
            variants:
                symfony/symfony: ['4.4.*']
                sonata-project/block-bundle: ['3.*']

form-extensions:
    has_test_kernel: false
    branches:
        2.x:
            php: ['8.0', '8.1']
            frontend: true
            variants:
                symfony/symfony: ['5.4.*', '6.0.*']
        1.x:
            php: ['7.4', '8.0', '8.1']
            frontend: true
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

intl-bundle:
    rector: false
    has_test_kernel: false
    branches:
        3.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        2.x:
            php: ['7.3', '7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
                sonata-project/user-bundle: ['4.*']

media-bundle:
    rector: false
    phpunit_extensions: ['doctrine_test']
    documentation_badge_slug: sonata-project-sonatamediabundle
    branches:
        5.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        4.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

page-bundle:
    rector: false
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        4.x:
            php: ['7.4', '8.0']
            variants:
                symfony/symfony: ['4.4.*']
                sonata-project/block-bundle: ['3.*']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4.*']
                sonata-project/block-bundle: ['3.*']

seo-bundle:
    rector: false
    has_test_kernel: false
    branches:
        4.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        3.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

translation-bundle:
    rector: false
    branches:
        4.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['pdo_sqlite']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        3.x:
            php: ['7.4', '8.0', '8.1']
            php_extensions: ['pdo_sqlite']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

twig-extensions:
    rector: false
    documentation_badge_slug: sonata-project-twig-extensions
    branches:
        2.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        1.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']

user-bundle:
    rector: false
    phpunit_extensions: ['doctrine_test']
    branches:
        6.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        5.x:
            php: ['7.4', '8.0', '8.1']
            variants:
                symfony/symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
