admin-bundle:
    phpstan: true
    psalm: true
    custom_gitattributes_part: |
        .phpstan export-ignore

    custom_gitignore_part: |
        # clean up some non bower ready package
        src/Resources/public/vendor/admin-lte/bootstrap
        src/Resources/public/vendor/admin-lte/build
        src/Resources/public/vendor/admin-lte/dist/img
        !src/Resources/public/vendor/admin-lte/dist/img/boxed-bg.jpg # Only image called in AdminLTE.css
        src/Resources/public/vendor/admin-lte/dist/js/app.js
        src/Resources/public/vendor/admin-lte/dist/js/demo.js
        src/Resources/public/vendor/admin-lte/dist/js/pages
        src/Resources/public/vendor/admin-lte/documentation
        src/Resources/public/vendor/admin-lte/pages
        src/Resources/public/vendor/admin-lte/plugins
        src/Resources/public/vendor/admin-lte/*.html
        src/Resources/public/vendor/admin-lte/Gruntfile.js

        src/Resources/public/vendor/iCheck/skins/all.css
        src/Resources/public/vendor/iCheck/skins/*/*
        !src/Resources/public/vendor/iCheck/skins/square/blue.css
        !src/Resources/public/vendor/iCheck/skins/square/blue.png
        !src/Resources/public/vendor/iCheck/skins/square/blue@2x.png
        src/Resources/public/vendor/iCheck/icheck.js

        src/Resources/public/vendor/slimScroll/examples
        src/Resources/public/vendor/slimScroll/jquery.slimscroll.js

        src/Resources/public/vendor/bootstrap/grunt
        src/Resources/public/vendor/bootstrap/less
        src/Resources/public/vendor/bootstrap/test-infra
        src/Resources/public/vendor/bootstrap/Gruntfile.js

        src/Resources/public/vendor/jqueryui/themes/black-tie
        src/Resources/public/vendor/jqueryui/themes/blitzer
        src/Resources/public/vendor/jqueryui/themes/cupertino
        src/Resources/public/vendor/jqueryui/themes/dark-hive
        src/Resources/public/vendor/jqueryui/themes/dot-luv
        src/Resources/public/vendor/jqueryui/themes/eggplant
        src/Resources/public/vendor/jqueryui/themes/excite-bike
        src/Resources/public/vendor/jqueryui/themes/hot-sneaks
        src/Resources/public/vendor/jqueryui/themes/humanity
        src/Resources/public/vendor/jqueryui/themes/le-frog
        src/Resources/public/vendor/jqueryui/themes/mint-choc
        src/Resources/public/vendor/jqueryui/themes/overcast
        src/Resources/public/vendor/jqueryui/themes/pepper-grinder
        src/Resources/public/vendor/jqueryui/themes/redmond
        src/Resources/public/vendor/jqueryui/themes/smoothness
        src/Resources/public/vendor/jqueryui/themes/south-street
        src/Resources/public/vendor/jqueryui/themes/start
        src/Resources/public/vendor/jqueryui/themes/sunny
        src/Resources/public/vendor/jqueryui/themes/swanky-purse
        src/Resources/public/vendor/jqueryui/themes/trontastic
        src/Resources/public/vendor/jqueryui/themes/ui-darkness
        src/Resources/public/vendor/jqueryui/themes/ui-lightness
        src/Resources/public/vendor/jqueryui/themes/vader

        src/Resources/public/vendor/jquery/src

        src/Resources/public/vendor/jquery.scrollTo/demo
        src/Resources/public/vendor/jquery.scrollTo/tests

    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
                sonata-project/block-bundle: ['4']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/block-bundle: ['3']

admin-search-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                ruflin/elastica: ['5', '6']
        1.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                ruflin/elastica: ['5', '6']

article-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
        1.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']

block-bundle:
    phpstan: true
    psalm: true
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        4.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']

cache:
    excluded_files:
        - README.md
    has_documentation: false
    branches:
        master:
            php: ['7.3', '7.4']
        2.x:
            php: ['7.3', '7.4']

cache-bundle:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']

classification-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0]
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
            tools: [pecl]
        3.x:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0]
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
            tools: [pecl]

classification-media-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']

comment-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
        3.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']

dashboard-bundle:
    custom_gitignore_part: |
        /.sass-cache
        /node_modules
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']

datagrid-bundle:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']

doctrine-extensions:
    phpstan: true
    psalm: true
    excluded_files:
        - README.md
    has_documentation: false
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            php_extensions: [mongodb-1.9.0]
            tools: [pecl]
            target_php: '7.4'
        1.x:
            php: ['7.3', '7.4', '8.0']
            php_extensions: [mongodb-1.9.0]
            tools: [pecl]
            target_php: '7.4'

doctrine-mongodb-admin-bundle:
    phpstan: true
    psalm: true
    panther: true
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            php_extensions: [mongodb-1.9.0]
            tools: [pecl]
            target_php: '7.4'
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['dev-master']
        3.x:
            php: ['7.3', '7.4', '8.0']
            php_extensions: [mongodb-1.9.0]
            tools: [pecl]
            target_php: '7.4'
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']

doctrine-orm-admin-bundle:
    phpstan: true
    psalm: true
    panther: true
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['dev-master']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']

doctrine-phpcr-admin-bundle:
    custom_gitignore_part: |
        tests/Fixtures/App/app.sqlite
    custom_doctor_rst_whitelist_part:
        "    - '.. _`cmf-sandbox configuration`: https://github.com/symfony-cmf/cmf-sandbox/blob/master/app/config/config.yml'"
    excluded_files:
        - tests/bootstrap.php
        - phpunit.xml.dist
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']
        2.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']

ecommerce:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
        3.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']

entity-audit-bundle:
    excluded_files:
        - LICENSE
        - README.md
    has_documentation: false
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
        1.x:
            php: ['7.3', '7.4', '8.0']

exporter:
    excluded_files:
        - README.md
    branches:
        master:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0]
            variants:
                symfony/symfony: ['4.4', '5.2']
            tools: [pecl]
        2.x:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0]
            variants:
                symfony/symfony: ['4.4', '5.2']
            tools: [pecl]

formatter-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/block-bundle: ['3']
        4.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/block-bundle: ['3']

form-extensions:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        1.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']

google-authenticator:
    excluded_files:
        - README.md
    has_documentation: false
    branches:
        master:
            php: ['7.3', '7.4']
        2.x:
            php: ['7.3', '7.4']

intl-bundle:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            target_php: '7.4'
            variants:
                symfony/symfony: ['4.4', '5.2']
        2.x:
            php: ['7.3', '7.4', '8.0']
            target_php: '7.4'
            variants:
                symfony/symfony: ['4.4', '5.2']
                sonata-project/user-bundle: ['4']

media-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0, soap, gd]
            tools: [pecl]
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                imagine/imagine: ['0.7', '1']
        3.x:
            php: ['7.3', '7.4']
            php_extensions: [mongodb-1.9.0, soap, gd]
            tools: [pecl]
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                imagine/imagine: ['0.7', '1']

news-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
        3.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']

notification-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        3.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']

page-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']
        3.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']

sandbox:
    has_documentation: false
    phpstan: true
    excluded_files:
        - .gitignore
        - Makefile
        - phpunit.xml.dist
        - README.md
    branches:
        master:
            php: ['7.4']

seo-bundle:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        2.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/block-bundle: ['3']
                sonata-project/admin-bundle: ['3']

timeline-bundle:
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']
        3.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']
                sonata-project/block-bundle: ['3']

translation-bundle:
    phpstan: true
    psalm: true
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['dev-master']
        2.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4']
                sonata-project/admin-bundle: ['3']

twig-extensions:
    branches:
        master:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']
        1.x:
            php: ['7.3', '7.4', '8.0']
            variants:
                symfony/symfony: ['4.4', '5.2']

user-bundle:
    custom_doctor_rst_whitelist_part:
        "    - 'resource: \"@NelmioApiDocBundle/Resources/config/routing.yml\"'"
    branches:
        master:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                friendsofsymfony/user-bundle: ['2']
                sonata-project/admin-bundle: ['3']
        4.x:
            php: ['7.3', '7.4']
            variants:
                symfony/symfony: ['4.4']
                friendsofsymfony/user-bundle: ['2']
                sonata-project/admin-bundle: ['3']
