admin-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_block: ['3']

admin-search-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_admin: ['3']
        ruflin_elastica: ['2']
    1.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']
        sonata_admin: ['3']
        ruflin_elastica: ['2']

article-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

block-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        # https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/131844587#L222
        #sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        # This has to be resolved: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/130298942#L230
        #sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests

cache:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    2.x:
      php: ['7.1']

cache-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

classification-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']

classification-media-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

comment-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
      docs_path: Resources/doc
      tests_path: Tests
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
      docs_path: Resources/doc
      tests_path: Tests

core-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

dashboard-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

datagrid-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

doctrine-extensions:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    1.x:
      php: ['5.6', '7.0', '7.1']

doctrine-mongodb-admin-bundle:
  branches:
    master:
      php: ['7.1']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests
    3.x:
      php: ['5.6', '7.0', '7.1']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests

doctrine-orm-admin-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']

doctrine-phpcr-admin-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']
        sonata_block: ['3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_admin: ['3']
        sonata_block: ['3']

easy-extends-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']

ecommerce:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']

exporter:
  excluded_files:
    - README.md
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        doctrine_odm: ['1']
      services: [mongodb]
    1.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        doctrine_odm: ['1']
      services: [mongodb]

formatter-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_block: ['3']

google-authenticator:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    2.x:
      php: ['7.1']

intl-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_user: ['3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_user: ['3']

media-bundle:
  branches:
    master:
      php: ['7.1']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.2', '3.3']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.2', '3.3']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']

news-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_user: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_user: ['3']

notification-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']

page-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

propel-admin-bundle: ~

sandbox: ~

seo-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_block: ['3']
        sonata_admin: ['3']
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_block: ['3']
        sonata_admin: ['3']

timeline-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

translation-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests
    2.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        sonata_core: ['3']
        sonata_admin: ['3']
      docs_path: Resources/doc
      tests_path: Tests

user-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.2', '3.3']
        fos_user: ['2']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8']
        fos_user: ['1.3']
        sonata_core: ['3']
        sonata_admin: ['3']
