admin-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_block: ['3']

admin-search-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_admin: ['3']
        ruflin_elastica: ['2']
    1.x:
      php: ['5.6', '7.0']
      versions:
        symfony: ['2.8']
        sonata_admin: ['3']
        ruflin_elastica: ['2']

article-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']

block-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        # https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/131844587#L222
        #sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        # This has to be resolved: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/130298942#L230
        #sonata_admin: ['3']

cache:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    1.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']

cache-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']

classification-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_admin: ['3']

classification-media-bundle:
  branches:
    master:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.0', '3.1']

comment-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
        sonata_core: ['3']

core-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']

dashboard-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

datagrid-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']

doctrine-extensions:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    1.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']

doctrine-mongodb-admin-bundle:
  branches:
    master:
      php: ['5.6']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6']
      services: [mongodb]
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_admin: ['3']

doctrine-orm-admin-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']

doctrine-phpcr-admin-bundle:
  branches:
    master:
      # sonata 2 should still support php 5.6 to be consistent with the symfony cmf
      php: ['5.6', '7.0', '7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_admin: ['3']
        sonata_block: ['3']
    1.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
        sonata_admin: ['3']
        sonata_block: ['3']

easy-extends-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']

ecommerce:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
      docs_path: docs
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
      docs_path: docs

exporter:
  excluded_files:
    - README.md
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        doctrine_odm: ['1']
      services: [mongodb]
      docs_path: docs
    1.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      target_php: 5.6
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        doctrine_odm: ['1']
      services: [mongodb]
      docs_path: docs

formatter-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_block: ['3']

google-authenticator:
  excluded_files:
    - README.md
  docs_target: false
  branches:
    master:
      php: ['7.1']
    2.x:
      php: ['7.0', '7.1']
    1.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']

intl-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_user: ['3']
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_user: ['3']

media-bundle:
  branches:
    master:
      php: ['7.1']
      services: [mongodb]
      versions:
        symfony: ['2.8', '3.1', '3.2']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      services: [mongodb]
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        doctrine_odm: ['1']
        sonata_core: ['3']
        sonata_admin: ['3']

news-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_user: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_user: ['3']

notification-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']

page-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

propel-admin-bundle: ~

sandbox: ~

seo-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_block: ['3']
        sonata_admin: ['3']
    2.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_block: ['3']
        sonata_admin: ['3']

timeline-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']
        sonata_block: ['3']

translation-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']
    2.x:
      php: ['5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8', '3.1', '3.2']
        sonata_core: ['3']
        sonata_admin: ['3']

user-bundle:
  branches:
    master:
      php: ['7.1']
      versions:
        symfony: ['2.8', '3.1', '3.2']
        fos_user: ['2']
        sonata_core: ['3']
        sonata_admin: ['3']
    3.x:
      php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1']
      versions:
        symfony: ['2.3', '2.7', '2.8']
        fos_user: ['1.3']
        sonata_core: ['3']
        sonata_admin: ['3']
