admin-bundle:
    documentation_badge_slug: sonata-project-sonataadminbundle
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

block-bundle:
    branches:
        6.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

classification-bundle:
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

doctrine-extensions:
    has_documentation: false
    has_test_kernel: false
    branches:
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
        2.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']

doctrine-mongodb-admin-bundle:
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

doctrine-orm-admin-bundle:
    documentation_badge_slug: sonata-project-doctrineormadminbundle
    has_platform_tests: true
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

entity-audit-bundle:
    excluded_files:
        - README.md
    has_documentation: false
    has_test_kernel: false
    has_platform_tests: true
    branches:
        2.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        1.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

exporter:
    documentation_badge_slug: sonata-project-exporter
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

formatter-bundle:
    branches:
        6.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

form-extensions:
    has_test_kernel: false
    branches:
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            frontend_tests: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        2.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            frontend_tests: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

intl-bundle:
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

media-bundle:
    documentation_badge_slug: sonata-project-sonatamediabundle
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb', 'gd']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

page-bundle:
    branches:
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            frontend: true
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

seo-bundle:
    has_test_kernel: false
    branches:
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

translation-bundle:
    branches:
        4.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

twig-extensions:
    documentation_badge_slug: sonata-project-twig-extensions
    branches:
        3.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        2.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']

user-bundle:
    branches:
        6.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
        5.x:
            php: ['8.1', '8.2', '8.3', '8.4']
            php_extensions: ['mongodb']
            variants:
                symfony/symfony: ['6.4.*', '7.1.*', '7.2.*']
